//
//  ProductListInteractor.swift
//  ProductSales
//
//  Created by Yeşim Daşdemir on 23.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListBusinessLogic {
}

protocol ProductListDataStore {
}

final class ProductListInteractor: ProductListBusinessLogic, ProductListDataStore {
  var presenter: ProductListPresentationLogic?
  var worker: ProductListWorker?
}
