//
//  ProductListPresenter.swift
//  ProductSales
//
//  Created by Yeşim Daşdemir on 23.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListPresentationLogic {
    func presentProductList(response: ProductSales.GetProductList.Response)
}

final class ProductListPresenter: ProductListPresentationLogic {
  weak var viewController: ProductListDisplayLogic?
  
    func presentProductList(response: ProductSales.GetProductList.Response) {
        let singleItemViewModel = response.products.map { item in
            SingleItemViewModel(id: item.productId,
                                title: item.productName,
                                subTitle: "deneme",
                                imageLink: item.productImage)
        }
        
        let productListViewModel = ProductSales.GetProductList.ViewModel(singleItemViewModel: singleItemViewModel,
                                                                         pageNo: response.pageCount)
        
        viewController?.displayProductList(viewModel: productListViewModel)
    }
}
