//
//  ProductListWorker.swift
//  ProductSales
//
//  Created by Yeşim Daşdemir on 23.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct ProductListRequest: RequestType {
    typealias Response = ProductSales.GetProductList.Response
    
    var parameterQuery: [URLQueryItem] = []
    
    var path: String {
        return "/ios-assignment/search"
    }
    
    var httpMethod: HTTPMethod {
        return .get
    }
    
    var queryItems: [URLQueryItem]? {
        get {
            parameterQuery
        }
        set {
            parameterQuery = newValue ?? []
        }
    }
}
