//
//  ProductListRouter.swift
//  ProductSales
//
//  Created by Yeşim Daşdemir on 23.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductListRoutingLogic {
}

protocol ProductListDataPassing {
  var dataStore: ProductListDataStore? { get }
}

final class ProductListRouter: NSObject, ProductListRoutingLogic, ProductListDataPassing {
  weak var viewController: ProductListViewController?
  var dataStore: ProductListDataStore?
  
  // MARK: Routing

  // MARK: Navigation

  // MARK: Passing data

}
