//
//  ProductListModels.swift
//  ProductSales
//
//  Created by Yeşim Daşdemir on 23.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductSales {
    enum GetProductList {
        struct Request {
        }
        
        struct Response: Decodable {
            let products: [ProductItem]
            let currentPage: Int
            let pageSize: Int
            let totalResults: Int
            let pageCount: Int
        }
        
        struct ViewModel {
            let singleItemViewModel: [SingleItemViewModel]
            let pageNo: Int
        }
    }
}

// MARK: ViewModels

struct ProductItem: Decodable {
    let productId: Int?
    let productName: String?
    let productImage: String
    let reviewInformation: ReviewInformationItem?
    let availabilityState: Int?
    let nextDayDelivery: Bool
}

struct ReviewInformationItem: Decodable {
    let reviewSummary: ReviewSummaryItem?
}

struct ReviewSummaryItem: Decodable {
    let reviewAverage: Double
    let reviewCount: Int
}
